---
title: "More Bayesian models and looking at spatial autocorrelation"
output:
  html_document:
    df_print: paged
---

```{r setup}
library(tidyverse)
library(spatialOnco)
library(spatgraphs)
library(glmnetUtils)
library(brms)
library(bayesplot)
library(DHARMa)

DATA_PATH = '../data/nbhd_coord_schurch_2020/'
RESULTS_PATH = '../results/bayes_glmnet_nbhds_01082022/'
dir.create(RESULTS_PATH)
df = read_csv(paste0(DATA_PATH,'CRC_master.csv'))

spot.labels = c("15_A","15_B","16_A","16_B")
keep_types = unique(df$ClusterName)

nbhds = make_spot_nbhds(df,spot.labels,keep_types, radius=50)

```

```{r}
cv.fit.4.1 = run_model(cv.glmnet,
                      file = paste0(RESULTS_PATH,"cv.fit.4.1"),
                      formula = tumor.cells ~ 1 + (CD4..T.cells.CD45RO. + CD68.CD163..macrophages + CD8..T.cells + Tregs + vasculature + CD11b.CD68..macrophages + CD68..macrophages + stroma + plasma.cells+spot)^2,
                      data = nbhds,
                      family = poisson())

plot(cv.fit.4.1)
```

```{r}
# frequency of tumor cell counts
table(nbhds$tumor.cells)

hist(nbhds$tumor.cells, breaks = 0:22)

# get an idea of the dispersion parameter in each spot
nbhds %>% 
  group_by(spot) %>%
  summarise(d_tumor = var(tumor.cells)/mean(tumor.cells))
```


```{r eval=FALSE}
# This chunk mainly useful for GWR models (which I was unable to get working very well, the bandwidth estimation kept failing, likely because the design matrix was singular in some locations. Could try again)
cf = coef(cv.fit.4.1, s = "lambda.1se")
terms = rownames(cf)[cf[,1] != 0]
terms.keep = unique(str_replace_all(terms,"spot.*","spot"))
terms.keep = unique(terms[-grep("spot",terms)])

terms.keep = terms.keep[-1]
fm = paste0("tumor.cells ~ ",paste(terms.keep, collapse = " + "))

feats = nbhds %>%
  named_group_split(spot, keep = FALSE)

coords = df %>% 
  rename(spot = spots) %>%
  filter(spot %in% spot.labels) %>%
  select(spot,X,Y) %>%
  named_group_split(spot, keep = FALSE)

library(GWmodel)
spdfs = mapply(SpatialPointsDataFrame,coords,feats,SIMPLIFY = F)

spplot(spdfs[[1]],"tumor.cells")

```

### More Bayesian models

```{r}
fit.4.2 <- brm(formula = bf(tumor.cells ~ 1 + (CD4..T.cells.CD45RO. + CD68.CD163..macrophages + CD8..T.cells + Tregs + vasculature + CD11b.CD68..macrophages +spot)),
  family = negbinomial(),
  data = nbhds,
  iter = 2000,
  warmup = 1000,
  cores = 4,
  file = paste0(RESULTS_PATH,"fit.4.2")
) %>% add_criterion("loo")

summary(fit.4.2)

fit.4.3 <- brm(formula = bf(tumor.cells ~ 1 + (CD4..T.cells.CD45RO. + CD68.CD163..macrophages + CD8..T.cells + Tregs + vasculature + CD11b.CD68..macrophages +spot)),
  family = zero_inflated_negbinomial(),
  data = nbhds,
  iter = 2000,
  warmup = 1000,
  cores = 4,
  file = paste0(RESULTS_PATH,"fit.4.3")
) %>% add_criterion("loo")

check_brms(fit.4.2)

check.4.3 = check_brms(fit.4.3,plot = F)

summary(fit.4.3)

loo_compare(fit.4.2,fit.4.3)

plotResiduals(check.4.3, form = nbhds$CD4..T.cells.CD45RO.)
plotResiduals(check.4.3, form = nbhds$CD8..T.cells)
plotResiduals(check.4.3, form = nbhds$Tregs)
plotResiduals(check.4.3, form = nbhds$CD68.CD163..macrophages)
plotResiduals(check.4.3, form = nbhds$CD11b.CD68..macrophages)
```

## Posterior predictive checks
```{r}
y = nbhds$tumor.cells
yrep.4.2 <- posterior_predict(fit.4.2, ndraws = 500)
yrep.4.3 <- posterior_predict(fit.4.3, ndraws = 500)

ppc_dens_overlay(y,yrep.4.2)
ppc_dens_overlay(y,yrep.4.3)

```

```{r}
prop_zero <- function(x) mean(x == 0)
prop_zero(y)

ppc_stat(y, yrep.4.2, stat = "prop_zero", binwidth = 0.005)
ppc_stat(y, yrep.4.3, stat = "prop_zero", binwidth = 0.005)

dispersion <- function(x) var(x)/mean(x)

ppc_stat(y, yrep.4.2, stat = "dispersion", binwidth = 0.005)
ppc_stat(y, yrep.4.3, stat = "dispersion", binwidth = 0.005)

ppc_stat_grouped(y, yrep.4.3, group = nbhds$spot, stat = "prop_zero")
ppc_stat_grouped(y, yrep.4.3, group = nbhds$spot, stat = "dispersion")


d = nbhds[nbhds$spot == "15_A",]
fit.4.3b <- brm(formula = bf(tumor.cells ~ 1 + (CD4..T.cells.CD45RO. + CD68.CD163..macrophages + CD8..T.cells + Tregs + vasculature + CD11b.CD68..macrophages)),
  family = zero_inflated_negbinomial(),
  data = d,
  iter = 2000,
  warmup = 1000,
  cores = 4,
  file = paste0(RESULTS_PATH,"fit.4.3b")
) %>% add_criterion("loo")
check.4.3b = check_brms(fit.4.3b, plot = F)
testSpatialAutocorrelation(simulationOutput = check.4.3b, x = d$X, y= d$Y)

```


```{r}

fit.4.4 <- brm(formula = bf(tumor.cells ~ 1 + (CD4..T.cells.CD45RO. + CD68.CD163..macrophages + CD8..T.cells + Tregs + vasculature + CD11b.CD68..macrophages +spot), zi ~ spot),
  family = zero_inflated_negbinomial(),
  data = nbhds,
  # control = list(adapt_delta = 0.99),
  iter = 2000,
  warmup = 1000,
  cores = 4,
  file = paste0(RESULTS_PATH,"fit.4.4")
) %>% add_criterion("loo")

summary(fit.4.4)
yrep.4.4 <- posterior_predict(fit.4.4, ndraws = 500)

ppc_stat(y, yrep.4.4, stat = "prop_zero", binwidth = 0.005)

ppc_stat(y, yrep.4.4, stat = "dispersion", binwidth = 0.005)

ppc_stat_grouped(y, yrep.4.4, group = nbhds$spot, stat = "prop_zero")
ppc_stat_grouped(y, yrep.4.4, group = nbhds$spot, stat = "dispersion")

loo_compare(fit.4.2,fit.4.3,fit.4.4)
```


#### Spatial autocorrelation

```{r}
d = nbhds[nbhds$spot == "15_A",]
fit.4.5 <- brm(formula = bf(tumor.cells ~ 1 + (CD4..T.cells.CD45RO. + CD68.CD163..macrophages + CD8..T.cells + Tregs + CD11b.CD68..macrophages), zi ~ 1),
  family = zero_inflated_negbinomial(),
  data = d,
  # control = list(adapt_delta = 0.99),
  iter = 2000,
  warmup = 1000,
  cores = 4,
  file = paste0(RESULTS_PATH,"fit.4.5")
) %>% add_criterion("loo")
check.4.5 = check_brms(fit.4.5, plot = F)
testSpatialAutocorrelation(simulationOutput = check.4.5, x = d$X, y= d$Y)

tibble(X = d$X, Y = d$Y, res = check.4.5$scaledResiduals) %>%
  ggplot(aes(x = X, y = Y, colour = res)) +
  geom_point(alpha=0.7) + 
  scale_colour_gradient(low = "red", high = "blue")
```

#### Smooths and splines

```{r}
fit.4.7 <- brm(formula = bf(tumor.cells ~ 1 + (s(CD4..T.cells.CD45RO.,k=3) + s(CD68.CD163..macrophages,k=3) + CD8..T.cells + Tregs + CD11b.CD68..macrophages+spot)),
  family = negbinomial(),
  data = nbhds,
  # control = list(adapt_delta = 0.99),
  iter = 2000,
  warmup = 1000,
  cores = 4,
  file = paste0(RESULTS_PATH,"fit.4.7")
) %>% add_criterion("loo")

loo_compare(fit.4.2,fit.4.7)

fit.4.8 <- brm(formula = bf(tumor.cells ~ 1 + (CD4..T.cells.CD45RO. + CD68.CD163..macrophages + CD8..T.cells + Tregs + CD11b.CD68..macrophages+spot),zi ~ spot + CD8..T.cells),
  family = zero_inflated_negbinomial(),
  data = nbhds,
  # control = list(adapt_delta = 0.99),
  iter = 2000,
  warmup = 1000,
  cores = 4,
  file = paste0(RESULTS_PATH,"fit.4.8")
) %>% add_criterion("loo")

summary(fit.4.8)

loo_compare(fit.4.3,fit.4.8)




xtabs( ~ CD4..T.cells.CD45RO.+ tumor.cells+spot,data=nbhds)

```

