---
title: "EDA of cell types and biomarkers"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(PCAtools)
library(pheatmap)
DATA_PATH = '../data/nbhd_coord_schurch_2020/'
df = read_csv(paste0(DATA_PATH,'CRC_master.csv'))

d = df %>% select(X,Y,`CD44 - stroma`:`MMP12 - matrix metalloproteinase`,spots) %>%
  filter(spots == '15_A') %>%
  select(-spots)

MIN_DIST = 15

xy = d %>%
  dplyr::select(c(X,Y)) %>%
  rename(x = X,y=Y) %>%
  as.data.frame

# set.seed(2022); xy = spatialRF::thinning(xy,minimum.distance = MIN_DIST)

d = d %>%
  semi_join(.,xy,by=c("X"="x","Y"="y")) %>%
  mutate(obs = 1:nrow(.)) %>%
  select(-c(X,Y)) %>%
  rename_with(~sub(" .*", "", .x)) %>%
  rename_with(~sub("-",".",.x)) %>%
  select(-obs)


col.rel.nb <- spdep::graph2nb(spdep::relativeneigh(as.matrix(xy)), sym=TRUE)

C = spdep::nb2mat(col.rel.nb,style="B",zero.policy=T)
listw = spdep::mat2listw(C)
```

```{r}
library(caret)
apply(d,2,var)

p <- pca(d, center = T, scale = T)

biplot(p, showLoadings = TRUE, lab = NULL)

screeplot(p, axisLabSize = 18, titleLabSize = 22)

loadings(p)

p$rotated

plotloadings(p)

eigencorplot(p,metavars = c("CD44","FOXP3"))

colnames(d)

pc1 <- p$loadings[,1]

boxplot(pc1)

summary(pc1)


```

Prevalence in tumor cells

```{r}
d1 = df %>% select(X,Y,`CD44 - stroma`:`MMP12 - matrix metalloproteinase`,spots,ClusterName) %>%
  filter(spots == '15_A') %>%
  select(-spots) %>%
  rename(type = ClusterName)
range01 <- function(x){(x-min(x))/(max(x)-min(x))}

d1 %>%
  mutate(across(-type,.fns=~range01(.))) %>%
  filter(type == "tumor cells") %>%
  select(-c(type,X,Y)) %>%
  colMeans %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  as_tibble %>%
  rename(.,val = `.`) %>%
  filter(val >= 0.15) %>%
  ggplot(aes(x=rowname,y=val)) + 
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

d1 %>%
  mutate(across(-type,.fns=~range01(.))) %>%
  filter(type == "tumor cells") %>%
  select(-c(type,X,Y)) %>%
  colMeans %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  as_tibble %>%
  rename(.,val = `.`) %>%
  filter(val >= 0.15) %>%
  pull(rowname)
```
 markers to study
 
beta-catenin
PD-1
EGFR
p53
MMP12

Macrophages:

T cells:

Granulocytes:

Tregs

B cells

NK cells

Monocytes


```{r}
library(magrittr)
library(spatialOnco)
spot.labels = c("15_A")
keep_types = unique(df$ClusterName)

nbhds = make_spot_nbhds(df,spot.labels,keep_types, radius = 50)

df %>%
  filter(spots == "15_A") %$%
  table(ClusterName)
```

B cells
CD4+ T cells CD45RO+
CD68+ macrophages
CD68+CD163+ macrophages
CD8+ T cells
granulocytes
Tregs

```{r}
plot(col.rel.nb,xy)


nbareas <- function(nb,xy) {
  sapply(1:length(nb),function(i) {
    idx <- c(i,nb[[i]])
    c.hull = chull(xy$x[idx],xy$y[idx])
    geometry::polyarea(xy$x[idx[c.hull]],xy$y[idx[c.hull]])
  })
}

nb.ar <- nbareas(col.rel.nb,xy)

nb.ar[nb.ar == 0] = 0.5

cmarks = df %>%
  filter(spots == "15_A") %>%
  pull(ClusterName)
marks = levels(as.factor(df$ClusterName))
nbhds = sapply(1:length(col.rel.nb),function(i) {
    x = c(cmarks[i],cmarks[col.rel.nb[[i]]])
    x = factor(x,levels=marks)
    as.vector(table(x))
  })
nbhds = t(nbhds)
colnames(nbhds) = marks
nbhds

dens <- sweep(nbhds,1,nb.ar,"/") %>% as_tibble
var(dens)
markers = df %>%
  filter(spots == "15_A") %>%
  select((contains("beta-catenin") | contains("PD-1") | contains("EGFR") | contains("p53") | contains("MMP12")) & !contains("+") | ClusterName) 
mean_markers = sapply(1:length(col.rel.nb),function(i) { 
  x = markers %>%
    slice(c(i,col.rel.nb[[i]])) %>%
    filter(ClusterName != "tumor cells") %>%
    summarise(across(-ClusterName,.fns=mean)) %>%
    replace(is.na(.), 0)
  list(x)
})

mean_markers = bind_rows(mean_markers)

mean_markers

dens = dens %>% select(c(`B cells`,
                  `CD4+ T cells CD45RO+`,
                  `CD68+ macrophages`,
                  `CD68+CD163+ macrophages`,
                  `CD8+ T cells`,
                  `granulocytes`,
                  `Tregs`,
                  `tumor cells`))

d2 <- bind_cols(dens,mean_markers,xy) %>%
  drop_na() %>%
  filter(across(,.fns=~!is.infinite(.))) %>%
  mutate(across(-c(x,y),.fns=range01))
which(is.na(d2) | is.infinite(rowSums(d2)), arr.ind=TRUE)

d2 = d2 %>%
  select(caret::nearZeroVar(d2))
# pheatmap(cor(d2 %>% select(c(
#                   `CD4+ T cells CD45RO+`,
#                   `CD68+CD163+ macrophages`,
#                   `granulocytes`)),method = "spearman"))
pheatmap(cor(d2))

```

```{r}
library(rms)
library(spatialreg)
colnames(d2) <- make.names(names(d2))
# attach(d2)
m.1 <- errorsarlm(tumor.cells ~ rcs(granulocytes,3) + rcs(CD4..T.cells.CD45RO.,3)+
                                  rcs(CD68..macrophages,3) + rcs(CD68.CD163..macrophages,3) +
                                  rcs(CD8..T.cells,3) + rcs(beta.catenin...Wnt.signaling,3) +
                                  rcs(PD.1...checkpoint,3) + rcs(EGFR...signaling,3) +
                                  rcs(p53...tumor.suppressor,3) + rcs(MMP12...matrix.metalloproteinase,3),data = d2,listw)

m.2 <- errorsarlm(tumor.cells ~ rcs(granulocytes,3) +  rcs(PD.1...checkpoint,3) + 
                                rcs(granulocytes,3) %ia%  rcs(PD.1...checkpoint,3) +
                                 rcs(CD4..T.cells.CD45RO.,3)+
                                  rcs(CD68..macrophages,3) + rcs(CD68.CD163..macrophages,3) +
                                  rcs(CD8..T.cells,3) + rcs(beta.catenin...Wnt.signaling,3) +
                                  rcs(EGFR...signaling,3) +
                                  rcs(p53...tumor.suppressor,3) + rcs(MMP12...matrix.metalloproteinase,3),data = d2,listw)


spdep::moran.test(m.1$residuals,listw)
spdep::moran.test(m.2$residuals,listw)


summary(m.2)

anova(m.2)
```



