---
title: "Eigenvector spatial filtering and penalized zero-inflated models"
output: html_notebook
---

```{r}
library(tidyverse)
library(spatialOnco)
library(spatgraphs)
library(spatialRF)


DATA_PATH = '../data/nbhd_coord_schurch_2020/'
RESULTS_PATH = '../results/'
df = read_csv(paste0(DATA_PATH,'CRC_master.csv'))

spot.labels = c("15_A","15_B","16_A","16_B")
keep_types = unique(df$ClusterName)

nbhds = make_spot_nbhds(df,spot.labels,keep_types,radius=50)

morans.i <- function(v,xy) {
  w <- 1/as.matrix(stats::dist(xy))

  diag(w) <- 0
  spdep::moran.test(v,spdep::mat2listw(w))
}
```

```{r}
d = nbhds %>% filter(spot == "16_B")

xy = d %>%
  select(c(X,Y)) %>%
  rename(x = X,y=Y) %>%
  as.data.frame()

xy_thin = thinning(xy,minimum.distance = 10)
xy = xy_thin

distance.matrix = as.matrix(stats::dist(xy))

distance.thresholds <- c(100,500,1000,1500,2000)

sp_evecs = spatialRF::mem_multithreshold(distance.matrix = distance.matrix,
                                         distance.thresholds = distance.thresholds)

data = d %>%
  semi_join(.,xy,by=c("X"="x","Y"="y")) %>%
  select(-c(X,Y,spot))

X = model.matrix(~ (CD4..T.cells.CD45RO. + CD68.CD163..macrophages + CD8..T.cells + Tregs + vasculature + CD11b.CD68..macrophages + CD68..macrophages + stroma + plasma.cells)^2,data) %>% as.matrix

X_sp = cbind(X,sp_evecs) %>% as.matrix
X_xy = cbind(X,xy$x,xy$y)
y = data %>% pull(tumor.cells)

cv.fit.1.1 <- run_model(glmnet::cv.glmnet, file = paste0(RESULTS_PATH,"cv.fit.1.1"),X_sp,y,family="poisson")
cv.fit.1.2 <- run_model(glmnet::cv.glmnet, file = paste0(RESULTS_PATH,"cv.fit.1.2"),X,y,family="poisson")
cv.fit.1.3 <- run_model(glmnet::cv.glmnet, file = paste0(RESULTS_PATH,"cv.fit.1.3"),X_xy,y,family="poisson")

coef(cv.fit.1.3)

plot(cv.fit.1.1)

coef(cv.fit.1.1,s="lambda.1se")

ypred = predict(cv.fit.1.1,newx = X_sp, type = "response")
res = y - ypred
res = (res - min(res)) / (max(res)-min(res))

morans.i(res,xy)
tibble(X = xy$x, Y = xy$y, res = res) %>%
  ggplot(aes(x = X, y = Y, colour = res)) +
  geom_point(alpha=0.7) + 
  scale_colour_gradient(low = "red", high = "blue")

coef(cv.fit.1.2)

hist(ypred)
hist(res)





```

```{r}
ypred = predict(cv.fit.1.2,newx = X, type = "response")
res = y - ypred
res = (res - min(res)) / (max(res)-min(res))
tibble(X = xy$x, Y = xy$y, res = res) %>%
  ggplot(aes(x = X, y = Y, colour = res)) +
  geom_point(alpha=0.7) + 
  scale_colour_gradient(low = "red", high = "blue")
morans.i(res,xy)

```

```{r}
ypred = predict(cv.fit.1.3,newx = X_xy, type = "response")
res = y - ypred
res = (res - min(res)) / (max(res)-min(res))
tibble(X = xy$x, Y = xy$y, res = res) %>%
  ggplot(aes(x = X, y = Y, colour = res)) +
  geom_point(alpha=0.7) + 
  scale_colour_gradient(low = "red", high = "blue")
```

#### Penalized zero-inflated models

```{r}
library(mpath)
data = d %>%
  semi_join(.,xy,by=c("X"="x","Y"="y")) %>%
  select(-c(X,Y,spot))
predictor.variable.names = colnames(d %>% select(-c(X,Y,spot,tumor.cells)))

sum(apply(data, 2, is.na))

predictor.variable.names = predictor.variable.names[apply(data[,predictor.variable.names], 2, var) != 0]

apply(data[,predictor.variable.names], 2, var) != 0
predictor.variable.names = predictor.variable.names[predictor.variable.names != "dirt"]

sum(predictor.variable.names %in% sapply(as.data.frame(scale(data)), function(x)any(is.nan(x))))

sapply(as.data.frame(scale(data)), function(x)any(is.infinite(x)))

predictor.variable.names

data = data[,apply(data,2,var) != 0]

fit.1.3 = zipath(formula=tumor.cells ~ CD4..T.cells.CD45RO. + CD68.CD163..macrophages + CD8..T.cells + Tregs + vasculature + CD11b.CD68..macrophages + CD68..macrophages + plasma.cells + stroma | 1,data=data,family="negbin")

X = model.matrix(tumor.cells ~ (CD4..T.cells.CD45RO. + CD68.CD163..macrophages + CD8..T.cells + Tregs + vasculature + CD11b.CD68..macrophages + CD68..macrophages + stroma + plasma.cells)^2,data) %>% as.data.frame
X = X[,apply(X,2,var) != 0]
X = cbind(tumor.cells=data$tumor.cells,X)



fit.1.3 = zipath(tumor.cells ~ CD4..T.cells.CD45RO. + CD68.CD163..macrophages + CD8..T.cells + Tregs + vasculature + CD11b.CD68..macrophages + CD68..macrophages + plasma.cells + stroma | Tregs + vasculature, data=data, family="negbin")

cv.fit.1.3 = cv.zipath(tumor.cells ~ CD4..T.cells.CD45RO. + CD68.CD163..macrophages + CD8..T.cells + Tregs + vasculature + CD11b.CD68..macrophages + CD68..macrophages + plasma.cells + stroma | Tregs + vasculature, data=data, family="negbin")


fit.1.4 = zipath(tumor.cells ~ . | ., data=X, family="negbin")

cv.fit.1.4 = cv.zipath(tumor.cells ~ . | ., data=X, family="negbin")


plot(cv.fit.1.3)

summary(cv.fit.1.3)

coef(fit.1.3,which=cv.fit.1.3$lambda.which)

cv.fit.1.3$bic

cv.fit.1.3

coef(fit.1.4)$count[,75]
```

