---
title: "spaMM for tumor cell neighborhoods"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(spatialOnco)
library(spatgraphs)
library(DHARMa)
library(spdep)
library(spaMM)

DATA_PATH = '../data/nbhd_coord_schurch_2020/'
RESULTS_PATH = '../../results/spamm_01232020/'
dir.create(RESULTS_PATH)
df = read_csv(paste0(DATA_PATH,'CRC_master.csv'))

spot.labels = c("15_A","15_B","16_A","16_B")
keep_types = unique(df$ClusterName)

nbhds = make_spot_nbhds(df,spot.labels,keep_types, radius=50)

d = nbhds %>% filter(spot == "15_A")
MIN_DIST = 25

xy = d %>%
  dplyr::select(c(X,Y)) %>%
  rename(x = X,y=Y) %>%
  as.data.frame

set.seed(2022); xy = spatialRF::thinning(xy,minimum.distance = MIN_DIST)

d = d %>%
  semi_join(.,xy,by=c("X"="x","Y"="y")) %>%
  mutate(obs = 1:nrow(.))

col.rel.nb <- graph2nb(relativeneigh(as.matrix(xy)), sym=TRUE)

C = spdep::nb2mat(col.rel.nb,style="B",zero.policy=T)
```

```{r}
pheatmap::pheatmap(cor(d %>% select(-c(X,Y,spot))),cluster_rows = F,cluster_cols = F)
```


```{r}
m.1 <- fitme(tumor.cells ~ B.cells + CD8..T.cells + vasculature + Matern(1|X+Y),fixed=list(nu=0.5), data=d,family = "poisson")

check.1 <-simulateResiduals(m.1,plot=T)

summary(m.1)

predict(m.1,type = "response")

plotResiduals(check.1, form = d$B.cells)
```

